name: CI
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install cmake help2man bats faketime
      - name: Build PostSRSd
        run: |
          make VERBOSE=ON
      - name: Run unit tests
        run: |
          make test
      - name: Run PostSRSd blackbox tests
        run: |
          ./run_postsrsd_tests.bats
      - name: Install PostSRSd
        run: |
          sudo make install
      - name: Check systemd service file
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start postsrsd || ( sudo systemctl status postsrsd ; exit 1 )
          sudo systemctl stop postsrsd
