name: clang-format
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '11'

